# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: connections.proto
# Protobuf Python Version: 4.25.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x11\x63onnections.proto\"^\n\x11\x43onnectionRequest\x12\x11\n\tperson_id\x18\x01 \x01(\t\x12\x12\n\nstart_date\x18\x02 \x01(\t\x12\x10\n\x08\x65nd_date\x18\x03 \x01(\t\x12\x10\n\x08\x64istance\x18\x04 \x01(\x05\"6\n\x12\x43onnectionResponse\x12 \n\x0b\x63onnections\x18\x01 \x03(\x0b\x32\x0b.Connection\"&\n\nConnection\x12\n\n\x02id\x18\x01 \x01(\t\x12\x0c\n\x04name\x18\x02 \x01(\t2N\n\x11\x43onnectionService\x12\x39\n\x0eGetConnections\x12\x12.ConnectionRequest\x1a\x13.ConnectionResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'connections_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  _globals['_CONNECTIONREQUEST']._serialized_start=21
  _globals['_CONNECTIONREQUEST']._serialized_end=115
  _globals['_CONNECTIONRESPONSE']._serialized_start=117
  _globals['_CONNECTIONRESPONSE']._serialized_end=171
  _globals['_CONNECTION']._serialized_start=173
  _globals['_CONNECTION']._serialized_end=211
  _globals['_CONNECTIONSERVICE']._serialized_start=213
  _globals['_CONNECTIONSERVICE']._serialized_end=291
# @@protoc_insertion_point(module_scope)
