apiVersion: v1
kind: Service
metadata:
  labels:
    service: udaconnect-kafka-broker
  name: udaconnect-kafka-broker
spec:
  ports:
  - name: "9092"
    port: 9092
    targetPort: 9092
    nodePort: 30005
  selector:
    service: udaconnect-kafka-broker
  type: NodePort
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    service: udaconnect-kafka-broker
  name: udaconnect-kafka-broker
spec:
  replicas: 1
  selector:
    matchLabels:
      service: udaconnect-kafka-broker
  template:
    metadata:
      labels:
        service: udaconnect-kafka-broker
    spec:
      containers:
      - image: apache/kafka:4.0.0
        name: udaconnect-kafka-broker
        imagePullPolicy: Always 
      restartPolicy: Always