apiVersion: v1
kind: Service
metadata:
  labels:
    service: udaconnect-kafka-broker
  name: udaconnect-kafka-broker
spec:
  ports:
  - name: "9092"
    port: 9092
    targetPort: 9092
    nodePort: 30005
  selector:
    service: udaconnect-kafka-broker
  type: NodePort
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    service: udaconnect-kafka-broker
  name: udaconnect-kafka-broker
spec:
  replicas: 1
  selector:
    matchLabels:
      service: udaconnect-kafka-broker
  template:
    metadata:
      labels:
        service: udaconnect-kafka-broker
    spec:
      containers:
      - env:
        - name: KAFKA_BROKER_ID
          value: 1
        - name: KAFKA_ENABLE_KRAFT
          value: yes
        - name: ALLOW_PLAINTEXT_LISTENER
          value: yes
        - name: KAFKA_CFG_PROCESS_ROLES
          value: broker,controller
        - name: KAFKA_LISTENERS
          value: PLAINTEXT://:9092
        - name: KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP
          value: CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT
        - name: KAFKA_ADVERTISED_LISTENERS
          value: PLAINTEXT://udaconnect-kafka-broker.default.svc.cluster.local:9092
      - image: apache/kafka:4.0.0
        name: udaconnect-kafka-broker
        imagePullPolicy: Always 
      restartPolicy: Always
